In [ ]:
!nvidia-smi

Thu Jun  8 06:37:55 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   58C    P8    11W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [ ]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

print(torch.__version__)

2.0.1+cu118


Introduction to tensors

Creating Tensors

In [ ]:
#scalar
import torch
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()

7

In [ ]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
#matrix
MATRIX = torch.tensor([[7,8],[9,2]])
MATRIX

tensor([[7, 8],
        [9, 2]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[0]

tensor([7, 8])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
#TENSOR
TENSOR = torch.tensor([[[1,2,3],[3,6,9],[7,8,9],[56,67,78]]])
TENSOR

tensor([[[ 1,  2,  3],
         [ 3,  6,  9],
         [ 7,  8,  9],
         [56, 67, 78]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 4, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [7, 8, 9]])

Random Tensors

Random tensors are important because the way neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data

In [ ]:
#Create a random tensor of size is [3,4]
random_tensor = torch.rand(2,3,4)
random_tensor

tensor([[[0.9427, 0.8496, 0.4842, 0.1623],
         [0.5542, 0.0896, 0.6023, 0.6690],
         [0.2548, 0.3910, 0.3996, 0.4857]],

        [[0.1046, 0.8448, 0.4010, 0.9061],
         [0.7758, 0.5759, 0.7881, 0.4955],
         [0.4492, 0.2687, 0.8597, 0.3809]]])

In [ ]:
random_tensor.ndim

3

In [ ]:
#create a random tensor with similar shape to an image tensor
T = torch.rand(size = (3,224,224))
T.shape, T.ndim

(torch.Size([224, 224, 3]), 3)

In [ ]:
zeros = torch.zeros(size = (3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
#Ctreating a range of tensors

In [ ]:
torch.arange(start = 1, end = 1000, step = 77)

tensor([  1,  78, 155, 232, 309, 386, 463, 540, 617, 694, 771, 848, 925])

In [ ]:
#tensor datatypes
float_32_tensor = torch.tensor([3.0,6.0,9.0],dtype = None)
float_32_tensor.dtype

torch.float32

 **Note:**

 Tensor datatypes is one of the 3 big errors you will run into with PyTorch and deep learning.

 1.Tensor not right datatype


 2.Tensors not right shape


 3.Tensors not on the right device

Manipulating Tensors

Tensor operations include:

1.Addtion

2.Multiplication

3.Subtraction

4.Division

5.Matrix Multiplication


In [ ]:

tensor = torch.tensor([1,2,3])
tensor + 10


tensor([11, 12, 13])

In [ ]:
tensor*10

tensor([10, 20, 30])

In [ ]:
tensor-10

tensor([-9, -8, -7])

In [ ]:
torch.mul(tensor,20)

tensor([20, 40, 60])

In [ ]:
T1 = torch.tensor([[3,5,8],[2,4,6]])
T1.shape
T2 = torch.tensor([[3,2],[5,4],[8,6]])
torch.matmul(T1,T2)


tensor([[98, 74],
        [74, 56]])

In [ ]:
T1.T

tensor([[3, 2],
        [5, 4],
        [8, 6]])

In [ ]:
x = torch.arange(10,20,1)
x

tensor([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
print(f"Mean: {x.type(torch.float32).mean()}")
print(f"Sum: {x.sum()}")


Minimum: 10
Maximum: 19
Mean: 14.5
Sum: 145


In [ ]:
torch.argmax(x)

tensor(9)

In [ ]:
T = torch.arange(10,100,10)
T.dtype

torch.int64

In [ ]:
T2 = T.type(torch.float16)
T2

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

In [ ]:
T_reshaped = T.reshape(1,9)
T_reshaped

tensor([[10, 20, 30, 40, 50, 60, 70, 80, 90]])

In [ ]:
x_stacked = torch.stack([T,T,T,T], dim = 0)
x_stacked

tensor([[10, 20, 30, 40, 50, 60, 70, 80, 90],
        [10, 20, 30, 40, 50, 60, 70, 80, 90],
        [10, 20, 30, 40, 50, 60, 70, 80, 90],
        [10, 20, 30, 40, 50, 60, 70, 80, 90]])

In [ ]:
x = torch.arange(1,10).reshape(1,3,3)

In [ ]:
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
x.[0]

SyntaxError: ignored

In [ ]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
x[0][0]

tensor([1, 2, 3])

In [ ]:
x[0][0][0]

tensor(1)

In [ ]:
print(f"{x[0][0][0]}")

1


In [ ]:
tensor = torch.from_numpy(x)
tnesor

TypeError: ignored

In [ ]:
tnesor

NameError: ignored

In [ ]:
tensor

tensor([1, 2, 3])

In [ ]:
A = torch.rand(3,4)
B = torch.rand(3,4)

In [ ]:
print(A)
print(B)


tensor([[0.3392, 0.5073, 0.7594, 0.3153],
        [0.8172, 0.2082, 0.2887, 0.2322],
        [0.9061, 0.5070, 0.7619, 0.1590]])
tensor([[0.3044, 0.4915, 0.9653, 0.6069],
        [0.6520, 0.6326, 0.8810, 0.0528],
        [0.1602, 0.9750, 0.0065, 0.3127]])


In [ ]:
random_seed = 42
torch.manual_seed(seed = random_seed)
C = torch.rand(3,4)
torch.manual_seed(seed = random_seed)

In [ ]:
D = torch.rand(3,4)
C == D


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [ ]:
print(C)
print(D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])


In [ ]:
import torch
tensor1 = torch.rand(7,7)
tensor1.shape

torch.Size([7, 7])

In [ ]:
tensor2 = torch.rand(1,7)

In [ ]:
torch.matmul(tensor1,tensor2.T)

tensor([[1.4733],
        [1.6478],
        [1.6012],
        [2.7491],
        [1.9943],
        [1.7917],
        [2.0712]])

In [ ]:
!nvidia-smi


Thu Jun  8 16:23:39 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   37C    P8     9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [ ]:
random_seed = 42
torch.manual_seed(seed = random_seed)
tensor1 = torch.rand(7,7)
torch.manual_seed(seed = random_seed)
tensor2 = torch.rand(1,7)
torch.matmul(tensor1,tensor2.T)

tensor([[3.2618],
        [3.4084],
        [2.4866],
        [1.4525],
        [1.7079],
        [2.7291],
        [2.9204]])